language: node_js
node_js: 9
install: npm install
script: npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: $EMAIL_ADDRESS
  api_key:
    secure: $ENCRYPTED_NPM_TOKEN
  on:
    branch: master

cache:
  directories:
  - node_modules